import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Entity News Aggregator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav><h1>Entity News Aggregator</h1></nav>
        {children}
      </body>
    </html>
  );
}
